In [1]:
import numpy as np

In [2]:
vector = [1,2,3]

In [3]:
print(type(vector))

<class 'list'>


In [4]:
nv = np.array(vector)

In [5]:
nv.shape

(3,)

In [6]:
mat = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [7]:
nmat = np.array(mat)

In [8]:
nmat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
nmat.shape

(3, 3)

In [10]:
j = 3
i = [1,2,3] #array
k = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
] #2D or matrix
x = [
    [[1,2,3],[6,2,3],[8,4,2]],
    [[5,2,3],[6,2,3],[8,4,2]],
    [[1,7,3],[6,2,3],[8,4,2]]
] #3D or Tensor

In [11]:
narr= np.array([1,2,3])
narr

array([1, 2, 3])

In [12]:
np.resize(narr,(4,5))


array([[1, 2, 3, 1, 2],
       [3, 1, 2, 3, 1],
       [2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2]])

In [13]:
narr.resize((3,3), refcheck = False)
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones((5,5)) #float

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.zeros((3,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.diag(narr) # it showed me the diagonal of narr

array([1, 0, 0])

In [17]:
np.repeat([4,3,2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [18]:
m1 = np.ones((5,5), int)
m1

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
m2 = np.zeros((5,5), int)
m2 #tuple

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
np.vstack([m1,m2]) # for vertical stack we have to same vertical size

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [21]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
z

array([5, 7, 9])

In [22]:
z = y // x
z # تقسیم صحیح

array([4, 2, 2])

In [23]:
x.dot(y) # 1*4+2*5+3*6                ضرب داخلی

32

In [24]:
narr.shape

(3, 3)

In [25]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [26]:
narr.T #transpose

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [27]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [28]:
narr.sum()

6

In [29]:
narr.max()

3

In [30]:
narr.min()

0

In [31]:
narr.argmax() #it show index of max value

2

In [32]:
narr.argmin()

3

In [33]:
narr.mean()

0.6666666666666666

In [34]:
narr.std() # انحراف استاندارد یا standard deviation        یعنی پراکندگی نسبت به میانگین

1.0540925533894598

In [35]:
mr = np.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [36]:
mr[1:5]

array([ 1,  4,  9, 16])

In [37]:
mr[14]

196

In [38]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [39]:
mr[-2:]

array([169, 196])

In [40]:
mr[2:-2]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [41]:
mr[2:10:2]

array([ 4, 16, 36, 64])

In [42]:
mr[10:2:-2]

array([100,  64,  36,  16])

In [43]:
mr[::-1]

array([196, 169, 144, 121, 100,  81,  64,  49,  36,  25,  16,   9,   4,
         1,   0])

In [44]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [45]:
narr[0:2, 1:3]

array([[2, 3],
       [0, 0]])

In [53]:
narr[::2,-1]

array([3, 0])

In [56]:
narr[narr >= 2]

array([2, 3])

In [57]:
narr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [63]:
marr = narr[-1]
marr

array([0, 0, 0])

In [67]:
marr[:] = 1
marr

array([1, 1, 1])

In [68]:
marr[:2] = 2
marr

array([2, 2, 1])

In [69]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [70]:
marr = narr.copy()
marr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [71]:
marr[:] = 0
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [72]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [73]:
tarr = np.random.randint(0, 10, (4, 3))
tarr

array([[5, 1, 9],
       [1, 0, 4],
       [3, 1, 7],
       [7, 3, 0]])

In [74]:
for r in tarr:
    print(r * 2)

[10  2 18]
[2 0 8]
[ 6  2 14]
[14  6  0]


In [76]:
for i, r in enumerate(tarr):
    print('index('+ str(i)+ ') is', r)

index(0) is [5 1 9]
index(1) is [1 0 4]
index(2) is [3 1 7]
index(3) is [7 3 0]


In [77]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 1]])

In [78]:
marr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [79]:
list(zip(narr, marr))

[(array([1, 2, 3]), array([0, 0, 0])),
 (array([0, 0, 0]), array([0, 0, 0])),
 (array([2, 2, 1]), array([0, 0, 0]))]

In [80]:
arr = [1,4,2,9,8,6,3]
arr = np.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [81]:
len(arr) // 2

3

In [83]:
p = arr[len(arr) // 2]
p

9

In [84]:
l = [x for x in arr if x < p]
l

[1, 4, 2, 8, 6, 3]

In [85]:
r = [x for x in arr if x > p]
r

[]

In [87]:
m = [x for x in arr if x == p]
m

[9]

In [88]:
l + m + r

[1, 4, 2, 8, 6, 3, 9]

In [91]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = np.array(arr)
    p = arr[len(arr) // 2]
    l = [x for x in arr if x < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [92]:
h = [3,6,4,1,3,9,4]
quicksort(h)

[1, 3, 3, 4, 4, 6, 9]

In [47]:
np.hstack([m1,m2])

array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]])

In [48]:
i = [1,2,5,7,13,17,19,23]
j = [2,4,6,8,10,12,14,16]
k = [1,2,3,4,5,6,7,8,9,10]

In [49]:
matrix= [i,j,k]

In [50]:
for x in (matrix):
    print(x)

[1, 2, 5, 7, 13, 17, 19, 23]
[2, 4, 6, 8, 10, 12, 14, 16]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [51]:
print(matrix[0:2])

[[1, 2, 5, 7, 13, 17, 19, 23], [2, 4, 6, 8, 10, 12, 14, 16]]


In [52]:
print(matrix[0][2])

5
